### ISSUE TITLE
Question

### ISSUE THREAD

**Issue by KartikChugh** [MatheusAvellar/gifski-win#1]
Was wondering how you made the Windows desktop app

**Comment by MatheusAvellar** [comment]
@KartikChugh It's [.NET software](https://dotnet.microsoft.com/apps/desktop), developed using [Visual Studio](https://visualstudio.microsoft.com/) with C#. It's pretty neat, you should try it out!

**Comment by KartikChugh** [comment]
Thanks! Is this project unmaintained, then?

**Comment by MatheusAvellar** [comment]
It's on the back burner for sure. I don't ever fully *give up* on projects I think are cool, but this one is not on the top of my priority list right now. :)
