### ISSUE TITLE
Unable to save results

### ISSUE THREAD

**Issue by Soul-Code** [MatheusAvellar/gifski-win#2]
![image](https://github.com/MatheusAvellar/gifski-win/assets/33421641/a563e1ee-ce9e-4d9b-85cb-cfa7df6fcf41)
After selecting the image, it will get stuck on this page.

**Comment by MatheusAvellar** [comment]
Hey! I'm sorry, I didn't mean to leave this project as if it was a finished product; I should've added a warning. This was an experiment inspired by a similar program on Mac, https://github.com/sindresorhus/Gifski.

I never did finish it though, and I am aware it's broken and doesn't work properly. Sorry!

I'll add a warning to the README and archive the repository so people are aware :) Thanks for trying it out, though!
